# **afficher les null et dublication**

In [2]:
import pandas as pd 
import os 

df = pd.read_csv('../data/data.csv')
df = df.drop('customerID',axis=1)
df = df.replace({
    'No internet service': 'No',
    'No phone service': 'No'
})
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df.dtypes

gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [4]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"],errors='coerce')
df.isna().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [5]:
df[df['TotalCharges'].isna()]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,Female,0,Yes,Yes,0,No,No,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,Male,0,No,Yes,0,Yes,No,No,No,No,No,No,No,No,Two year,No,Mailed check,20.25,NaN,No
936,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,Male,0,Yes,Yes,0,Yes,Yes,No,No,No,No,No,No,No,Two year,No,Mailed check,25.75,NaN,No
1340,Female,0,Yes,Yes,0,No,No,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,Male,0,Yes,Yes,0,Yes,No,No,No,No,No,No,No,No,Two year,No,Mailed check,19.85,NaN,No
3826,Male,0,Yes,Yes,0,Yes,Yes,No,No,No,No,No,No,No,Two year,No,Mailed check,25.35,NaN,No
4380,Female,0,Yes,Yes,0,Yes,No,No,No,No,No,No,No,No,Two year,No,Mailed check,20.00,NaN,No
5218,Male,0,Yes,Yes,0,Yes,No,No,No,No,No,No,No,No,One year,Yes,Mailed check,19.70,NaN,No
6670,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [6]:

df['TotalCharges']= df['TotalCharges'].fillna(0)
df.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
# var = df.loc[(df['InternetService'] == 'No') &(
#               (df['OnlineSecurity']!= 'No internet service')|
#               (df['OnlineBackup']!= 'No internet service') |
#               (df['DeviceProtection']!= 'No internet service') |
#               (df['TechSupport']!= 'No internet service') |
#               (df['StreamingTV']!= 'No internet service') |
#               (df['StreamingMovies']!= 'No internet service'))
#             ]

# var

In [8]:
# for col in df.select_dtypes(include="object").columns:
#     print("\n", col)
#     print(df[col].unique())

# df.select_dtypes(include="number").max()

# df["SeniorCitizen"].value_counts()
# df[df["tenure"] < 0]
# df[df["tenure"] == 0][
#     ["tenure", "MonthlyCharges", "TotalCharges"]
# ]

In [9]:
NUM = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

cat = df.drop(NUM,axis=1)

cat.columns
# df[NUM].dtypes
# for c in NUM:
#     Q1=df[c].quantile(0.25)
#     Q3=df[c].quantile(0.75)

#     iqr = Q3 - Q1

#     l = Q1 - 1.5 * iqr
#     u = Q3 + 1.5 * iqr

#     out = df[
#         (df[c] < l) |
#         (df[c] > u)
#     ]

#     print(c,":",len(out))

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn'],
      dtype='str')

## separation des X et Y

In [10]:
x = df.drop(['Churn'],axis=1)
y= df['Churn']

In [11]:
from sklearn.model_selection import train_test_split

x_train , x_test, y_train ,y_test= train_test_split(
    x,
    y,
    train_size=0.2,
    random_state=42
)

## Codage des colone en numeric

In [ ]:
string = x.select_dtypes(include='str').columns
NUM = x.select_dtypes(include='number').columns
NUM = NUM.drop('SeniorCitizen')

Index(['tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')

In [ ]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer


preprocessor = ColumnTransformer(
    transformers=[
        ('string',OneHotEncoder(handle_unknown='ignore'),string),
        ('NUM',StandardScaler(),NUM)
    ]
)

x_train_encoded= preprocessor.fit_transform(x_train)
1
x_test_encoded = preprocessor.transform(x_test)